<?php

return array(
        'listGroups' => 'groups-management',
        'newGroupPost' => 'groups-management',
        'newGroup' => 'groups-management',
        'deleteGroup' => 'groups-management',
        'showGroup' => 'groups-management',
        'putGroup' => 'groups-management',
        'listUsers' => 'view-users-list',
        'deleteUsers' => 'delete-user',
        'newUser' => 'create-user',
        'newUserPost' => 'create-user',
        'showUser' => 'update-user-info',
        'putUser' => 'update-user-info',
        'putActivateUser' => 'update-user-info',
        'deleteUserGroup' => 'user-group-management',
        'addUserGroup' => 'user-group-management',
        'listPermissions' => 'permissions-management',
        'deletePermission' => 'permissions-management',
        'newPermission' => 'permissions-management',
        'newPermissionPost' => 'permissions-management',
        'showPermission' => 'permissions-management',
        'putPermission' => 'permissions-management',
        'addUserPermission' => 'permissions-management',
        'addGroupPermission' => 'permissions-management',

        'admin-default'=> 'admin-default',

        'posts-list'=> 'posts-list',
        'posts-create'=>'posts-create',
        'posts-store'=>'posts-store',
        'posts-publish'=>'posts-publish',
        'posts-category'=>'posts-category',
        'posts-edit'=>'posts-edit',
        'posts-update'=>'posts-update',
        'posts-delete'=>'posts-delete',
        'posts-show'=>'posts-show',
        'tag_autocomplete'=>'tag_autocomplete',
        'posts-count-top-post'=>'posts-count-top-post',

        'category-list'=> 'category-list',
        'category-create'=>'category-create',
        'category-store'=>'category-store',
        'category-edit'=>'category-edit',
        'category-update'=>'category-update',
        'category-delete'=>'category-delete',
        'category-show'=>'category-show',
        'category-count'=>'category-count',

        'tag-list'=> 'tag-list',
        'tag-create'=>'tag-create',
        'tag-store'=>'tag-store',
        'tag-edit'=>'tag-edit',
        'tag-update'=>'tag-update',
        'tag-delete'=>'tag-delete',
        'tag-show'=>'tag-show',

        'album-list'=> 'album-list',
        'album-create'=>'album-create',
        'album-store'=>'album-store',
        'album-edit'=>'album-edit',
        'album-update'=>'album-update',
        'album-delete'=>'album-delete',
        'album-show'=>'album-show',

        'media-list'=> 'media-list',
        'media-create'=>'media-create',
        'media-store'=>'media-store',
        'media-edit'=>'media-edit',
        'media-update'=>'media-update',
        'media-delete'=>'media-delete',
        'media-show'=>'media-show',

        'setting-list'=> 'setting-list',
        'setting-create'=>'setting-create',
        'setting-store'=>'setting-store',
        'setting-edit'=>'setting-edit',
        'setting-update'=>'setting-update',
        'setting-delete'=>'setting-delete',
        'setting-show'=>'setting-show',

        'menu-list'=> 'menu-list',
        'menu-create'=>'menu-create',
        'menu-store'=>'menu-store',
        'menu-edit'=>'menu-edit',
        'menu-update'=>'menu-update',
        'menu-delete'=>'menu-delete',
        'menu-show'=>'menu-show',

        'comment-list'=> 'comment-list',
        'comment-create'=>'comment-create',
        'comment-store'=>'comment-store',
        'comment-edit'=>'comment-edit',
        'comment-update'=>'comment-update',
        'comment-delete'=>'comment-delete',
        'comment-show'=>'comment-show',
        'comment-action'=>'comment-action',

        'position-list'=> 'position-list',
        'position-create'=>'position-create',
        'position-store'=>'position-store',
        'position-edit'=>'position-edit',
        'position-update'=>'position-update',
        'position-delete'=>'position-delete',
        'position-show'=>'position-show',
        'position-action'=>'position-action',

        'staff-list'=> 'staff-list',
        'staff-create'=>'staff-create',
        'staff-store'=>'staff-store',
        'staff-edit'=>'staff-edit',
        'staff-update'=>'staff-update',
        'staff-delete'=>'staff-delete',
        'staff-show'=>'staff-show',
        'staff-action'=>'staff-action',

        'schedule-list'=> 'schedule-list',
        'schedule-create'=>'schedule-create',
        'schedule-store'=>'schedule-store',
        'schedule-edit'=>'schedule-edit',
        'schedule-update'=>'schedule-update',
        'schedule-delete'=>'schedule-delete',
        'schedule-show'=>'schedule-show',
        'schedule-action'=>'schedule-action',
        'schedule-count'=>'schedule-count',
);
